# ==== General Configuration ====
# Documentation of the TOML format: https://toml.io/en/latest

# Allow only a single vocabulary (default) or multiple vocabularies in the repository.
single_vocab = true

# ==== Configuration for vocabulary "voc4cat" ====

# The name of the vocabulary is used as section name.
# It should match the filename-stem of the vocabulary files.
[vocabs.voc4cat]
# Length of integer IDs in vocabulary. IDs will be left-padded with zeros to specified length.
id_length = 7
# permanent part of IRIs defined in the vocabulary
permanent_iri_part = "https://w3id.org/nfdi4cat/voc4cat_"

# Section to configure checks (useful in CI pipeline)
[vocabs.voc4cat.checks]
# Deleting allowed (relevant in CI-pipeline)
allow_delete = false

[vocabs.voc4cat.prefix_map]
v4c = "https://w3id.org/nfdi4cat/voc4cat_"
# Section of IDranges for coordinating the allocation of numeric ID ranges to
# contributors for each vocabulary. Each idrange contains the same keys:
#
# first_id = <int>            - first reserved integer ID in idrange
# last_id = <int>             - last reserved integer ID in idrange
# gh_name = "<string>"        - user or organisation name on github
# orcid = "<string> or <url>" - contributor's ORCID, e.g. "0000-0002-1825-0097" or "https://orcid.org/0000-0002-1825-0097"
# ror_id = "<url>"            - ROR identifier of home organisation, e.g. "https://ror.org/04fa4r544"

[[vocabs.voc4cat.id_range]]
first_id = 1
last_id = 5000
gh_name = "nmoust"
orcid = "0000-0002-6242-2167"
ror_id = "https://ror.org/029hg0311"

[[vocabs.voc4cat.id_range]]
first_id = 5001
last_id = 6000
gh_name = "dalito"
orcid = "0000-0002-5898-1820"
ror_id = "https://ror.org/029hg0311"

[[vocabs.voc4cat.id_range]]
first_id = 6001
last_id = 7000
gh_name = "markdoerr"
orcid = "0000-0003-3270-6895"
ror_id = "https://ror.org/00r1edq15"

[[vocabs.voc4cat.id_range]]
first_id = 7001
last_id = 7100
gh_name = "schumnannj"
orcid = "0000-0002-4041-0165"
ror_id = "https://ror.org/01hcx6992"

[[vocabs.voc4cat.id_range]]
first_id = 7101
last_id = 7200
gh_name = "HendrikBorgelt"
orcid = "0000-0001-5886-7860"
ror_id = "https://ror.org/01k97gp34"

# Continue with as many [[vocabs.voc4cat.id_range]] sections as needed.


# ==== Configuration for vocabulary "physics_chemistry" ====

[vocabs.physics_chemistry]
id_length = 7
permanent_iri_part = "https://w3id.org/nfdi4cat/voc4cat_physics_chemistry/"

[vocabs.physics_chemistry.checks]
allow_delete = false

[vocabs.physics_chemistry.prefix_map]
v4c-pc = "https://w3id.org/nfdi4cat/voc4cat_physics_chemistry/"

# ==== Configuration for vocabulary "catalysis" ====

[vocabs.catalysis]
id_length = 7
permanent_iri_part = "https://w3id.org/nfdi4cat/voc4cat_catalysis/"

[vocabs.catalysis.checks]
allow_delete = false

[vocabs.catalysis.prefix_map]
v4c-cat = "https://w3id.org/nfdi4cat/voc4cat_catalysis/"

# ==== Configuration for vocabulary "homogeneous_catalysis" ====

[vocabs.homogeneous_catalysis]
id_length = 7
permanent_iri_part = "https://w3id.org/nfdi4cat/voc4cat_homogeneous_catalysis/"

[vocabs.homogeneous_catalysis.checks]
allow_delete = false

[vocabs.homogeneous_catalysis.prefix_map]
v4c-hc = "https://w3id.org/nfdi4cat/voc4cat_homogeneous_catalysis/"

# heterogeneous catalysis vocabulary

# ==== Configuration for vocabulary "heterogeneous_catalysis" ====

[vocabs.heterogeneous_catalysis]
id_length = 7
permanent_iri_part = "https://w3id.org/nfdi4cat/voc4cat_heterogeneous_catalysis/"

[vocabs.heterogeneous_catalysis.checks]
allow_delete = false

[vocabs.heterogeneous_catalysis.prefix_map]
v4c-het = "https://w3id.org/nfdi4cat/voc4cat_heterogeneous_catalysis/"


# ==== Configuration for vocabulary "chemical_processes" ====

[vocabs.chemical_processes]
id_length = 7
permanent_iri_part = "https://w3id.org/nfdi4cat/voc4cat_chemical_processes/"

[vocabs.chemical_processes.checks]
allow_delete = false

[vocabs.chemical_processes.prefix_map]
v4c-cp = "https://w3id.org/nfdi4cat/voc4cat_chemical_processes/"



# ==== Configuration for vocabulary "photochemistry" ====

[vocabs.photochemistry]
id_length = 7

permanent_iri_part = "https://w3id.org/nfdi4cat/voc4cat_photochemistry/"

[vocabs.photochemistry.checks]
allow_delete = false

[vocabs.photochemistry.prefix_map]
v4c-pc = "https://w3id.org/nfdi4cat/voc4cat_photochemistry/"



# ==== Configuration for vocabulary "biocatalysis" ====

[vocabs.biocatalysis]
id_length = 7
permanent_iri_part = "https://w3id.org/nfdi4cat/voc4cat_biocatalysis/"

[vocabs.biocatalysis.checks]
allow_delete = false

[vocabs.biocatalysis.prefix_map]
v4c-bc = "https://w3id.org/nfdi4cat/voc4cat_biocatalysis/"

[[vocabs.biocatalysis.id_range]]
first_id = 1
last_id = 1000
gh_name = "markdoerr"
orcid = "0000-0003-3270-6895"
ror_id = "https://ror.org/00r1edq15"
